### ISSUE TITLE
Can a toast trigger its own removal?

### ISSUE THREAD

**Issue by mikos** [jossmac/react-toast-notifications#103]
I'm rendering a component within a Toast and would like to be able to remove the Toast under certain conditions for example, when a button is clicked or when an action has completed.

**Comment by jossmac** [comment]
The `addToast` method takes a third callback argument, you could use that. The `addToast` method also returns the `id` of the created toast.

Maybe checkout the ConnectivityListener's implementation: https://github.com/jossmac/react-toast-notifications/blob/master/examples/src/ConnectivityListener.js

**Comment by brettinternet** [comment]
@jossmac [I see](https://github.com/jossmac/react-toast-notifications/blob/c7d29510af63abd39537336a1a4be53367228dd2/src/ToastProvider.js#L120). We might update [the return type here](https://github.com/jossmac/react-toast-notifications/blob/c7d29510af63abd39537336a1a4be53367228dd2/index.d.ts#L63).
