### ISSUE TITLE
pauseOnHover: false is ignored

### ISSUE THREAD

**Issue by ImSolitude** [jossmac/react-toast-notifications#105]
I am not sure what I'm doing wrong, I have as simple as this toast,

![usetoast](https://user-images.githubusercontent.com/20565199/81743099-ce50b100-94a9-11ea-9702-1ec950b5f58a.png)

I am using custom `Snack` on `<ToastProvider/>`,

`components={{ Toast: Snack }}`

And this my custom one, 
![snack](https://user-images.githubusercontent.com/20565199/81743279-18d22d80-94aa-11ea-9014-40da86c62c51.png)

However, `pauseOnHover: false` is totally ignored.

**Comment by brettinternet** [comment]
I don't think `pauseOnHover` is an [acceptable option](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/864d6f31b9278a83e9c9af3de0a720e2e6246f19/types/react-toast-notifications/index.d.ts#L61-L65).

Please consider using code blocks instead of images for the sake of search and readability.

**Comment by jossmac** [comment]
@ImSolitude You're not doing anything wrong. I removed the option to disable pause on hover, because it would create a really bad user experience
