### ISSUE TITLE
Toast component should receive its `id` as prop

### ISSUE THREAD

**Issue by indigoviolet** [jossmac/react-toast-notifications#106]
Thanks for this library.

I noticed that you support setting `id` via `addToast`, but for some reason (because it's pulled out as `key` in `ToastController`) it isn't passed into the `Toast` component. Having this prop would make it easier to use `removeToast` from within the Toast component, for example to dismiss it on button click. 

Currently the slightly ugly work around is to set `id` as well as another prop (eg. `customId` ) with the same value in `addToast`, and then operate using `customId` in the Toast component.

**Comment by mikos** [comment]
This would help me with #103.

**Comment by indigoviolet** [comment]
> This would help me with #103.

@mikos, you can already use the workaround that I suggested to resolve #103.

**Comment by indigoviolet** [comment]
I also realized today that the typescript types for `addToast` don't mention `id`, or `customId` (or `autoDismissTimeout`) even though these work; and that `ToastProps` doesn't allow for `customId` to be passed in. Had to patch all these :vomiting_face: locally

**Comment by brettinternet** [comment]
I am able to invoke `onDismiss` passed from `ToastProps` in my custom `Toast` component without passing in an `id` as a parameter and it does indeed dismiss the toast.

**Comment by indigoviolet** [comment]
@brettinternet that makes sense - I didn't notice that parameter / realize that I could invoke it to dismiss. Perhaps this suggests an improvement to the docs, but besides that I think this issue can be closed.

**Comment by jossmac** [comment]
@indigoviolet please feel free to provide a PR with docs changes
