### ISSUE TITLE
Make it work on Strict Mode

### ISSUE THREAD

**Issue by brielov** [jossmac/react-toast-notifications#109]
I'm using react-toast-notifications inside react's `StrictMode` and I get the following error:

`Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by ToastElement)
    in ToastElement (created by DefaultToast)
    in DefaultToast (created by ToastController)
    in ToastController (created by Transition)
    in Transition (created by ToastProvider)
    in TransitionGroup (created by ToastProvider)
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by ToastContainer)
    in ToastContainer (created by ToastProvider)
    in ToastProvider (at src/index.js:18)
    in ApolloProvider (at src/index.js:17)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:16)
    in IdentityContextProvider (at src/index.js:15)
    in StrictMode (at src/index.js:14)`

**Comment by gcperrin** [comment]
Why is this closed? Still an issue.

**Comment by jossmac** [comment]
Duplicate of #82
