### ISSUE TITLE
Custom theme/appearance

### ISSUE THREAD

**Issue by klaaz0r** [jossmac/react-toast-notifications#11]
I love using the toast but was wondering if it is possible to theme the toasts, creating an custom toast is a bit overkill but something to set the default appearances on the base toast would be great! 

So the `ToastProvider` would take `appearances` prop, 
```
const appearances = {
  success: {
    icon: CheckIcon,
    text: colors.G500,
    fg: colors.G300,
    bg: colors.G50,
  },
  error: {
    icon: FlameIcon,
    text: colors.R500,
    fg: colors.R300,
    bg: colors.R50,
  },
  warning: {
    icon: AlertIcon,
    text: colors.Y500,
    fg: colors.Y300,
    bg: colors.Y50,
  },
  info: {
    icon: InfoIcon,
    text: colors.N400,
    fg: colors.B200,
    bg: 'white',
  },
};
```

**Comment by jossmac** [comment]
@klaaz0r I hear where you're coming from, but I've been down that path before and it only leads to heartache. What if the consumer wants and different font size? How about padding, where should that padding be applied; the wrapper, just the content?

As a maintainer you can tie yourself in knots trying to meet everyone's needs, whilst constantly increasing the complexity of the lib.

Sorry mate, it's not hard to knock-up a toast component. Check out the [Snackbar implementation](https://github.com/jossmac/react-toast-notifications/blob/master/examples/src/index.js#L34) for a good place to start.
