### ISSUE TITLE
Create a new release? 

### ISSUE THREAD

**Issue by willsoto** [jossmac/react-toast-notifications#120]
There have been quite a few useful improvements (including native typings) that would be nice to have published. Here is the diff between the last release `v2.4.0` and now: https://github.com/jossmac/react-toast-notifications/compare/86083a5..master

**Comment by maapteh** [comment]
Hi, is this project dead? I was thinking about making a mocked provider to make testing of components easier but if its dead i can use my time differently.

**Comment by jossmac** [comment]
@maapteh Yeah, there's other solutions now. You're probably better off spending your time elsewhere

**Comment by jossmac** [comment]
@jens-ox 

>  I just published a react notification system based on this package

Nice one!

> The only real difference is that no UI is provided by default

Definitely the right direction 🚀

**Comment by jossmac** [comment]
Version `2.4.1` is available with recent changes. Version `2.4.2` supports React 17
