### ISSUE TITLE
Fetch callback

### ISSUE THREAD

**Issue by jjoker0110** [jossmac/react-toast-notifications#124]
I'm newer to react so maybe I am overlooking this or not understanding but I'm trying to add a toast on a fetch callback but when I try to reference useToast inside a react component I get an invalid hook call. I can get it to work fine when I reference it outside the component and then add it in under the render function. I could just use a little push in the right direction. Thank you

**Comment by jjoker0110** [comment]
Nevermind, I figured it out using "withToastManager"

**Comment by jamesthesken** [comment]
Hey @jjoker0110 could you provide a snippet for your solution? I'm having a similar issue.

Thank you

**Comment by jjoker0110** [comment]
Hey @jamesthesken, it looks like you need to wrap the component in withToastManager. So something like this:
```
import { withToastManager } from 'react-toast-notifications';

class myCoolClass extends Component {
  state = {};
  constructor(props) {
    super(props);
  }

  testToastMsg = (msg) => {
    const { toastManager } = this.props;
    toastManager.add(msg, {
      appearance: 'info',
      autoDismiss: true,
    });
  }
  ....
}

export default withToastManager(myCoolClass);
```
Then just call testToastMsg("hello world!") with some message and that should work.

Hope that helps!

**Comment by jossmac** [comment]
For clarity; the issue here is trying to use hooks within a class component. From the [React Hooks FAQs](https://reactjs.org/docs/hooks-faq.html#should-i-use-hooks-classes-or-a-mix-of-both):

> You can’t use Hooks inside a class component, but you can definitely mix classes and function components with Hooks in a single tree.

You don't _have to_ use the higher order component, you can still use the hook and pass its value into the class component yourself.

```jsx
const FunctionalThing = props => {
  const toasts = useToast();

  return <ClassThing {...toasts} {...props} />
}

class ClassThing extends Component {
  someMethod = () => {
    const { addToast } = this.props;

    addToast('Toast content', {/* options */})
  }
}
```

**Comment by jjoker0110** [comment]
Ah, that helps, thank you @jossmac
