### ISSUE TITLE
dataPersistenceLayer is not defined

### ISSUE THREAD

**Issue by mikkhimself** [jossmac/react-toast-notifications#128]
Awesome work on the project
Im using the example code which can be found on the docs however I'm getting 
`dataPersistenceLayer is not defined`

With the following code: 

```
 const onSubmit = async value => {
    const { error } = await dataPersistenceLayer(value)

    if (error) {
      addToast(error.message, { appearance: 'error' })
    } else {
      addToast('Saved Successfully', { appearance: 'success' })
    }
  }
```

Is there something I'm missing?

**Comment by Carlock1609** [comment]
Was there a solution to this? I am also running into this issue

**Comment by jossmac** [comment]
The above is example code, so `dataPersistenceLayer` doesn't exist.
