### ISSUE TITLE
Is it possible to use this library outside a React Component?

### ISSUE THREAD

**Issue by Waqqars987** [jossmac/react-toast-notifications#133]
Hi,

I want to use the library where I use my axios interceptors to detect API responses. Its outside any React Component, hence I am unable to use this library there (rule of hooks). Is there any workaround for this?

**Comment by kalmndo** [comment]
yes i also had that problem, i use it outside the React component.
it doesn't work, the toast doesn't showed up.

**Comment by jossmac** [comment]
Please see issue #40, which goes into detail about this concern, how it may be resolved and why it will not be a supported feature.
