### ISSUE TITLE
Cannot read property 'bg' of undefined

### ISSUE THREAD

**Issue by AugustBemsen** [jossmac/react-toast-notifications#136]
I attached the Toast to a modal that makes a payment, the toast should appear when the use close the modal and cancel a payment, But i got this error instead 
![image](https://user-images.githubusercontent.com/54921134/98553860-59b3cf00-22a0-11eb-86a4-431b74f20955.png)

**Comment by coddingtonbear** [comment]
Just by the way @AugustBemsen  -- I think this is the issue you're running into: https://github.com/jossmac/react-toast-notifications/issues/23

**Comment by jossmac** [comment]
The [above comment](https://github.com/jossmac/react-toast-notifications/issues/136#issuecomment-725810987) should resolve the issue.

Please comment if you need this reopened.
