### ISSUE TITLE
Issue when placed next to a fixed header

### ISSUE THREAD

**Issue by vcanales** [jossmac/react-toast-notifications#14]
Thanks for the awesome library!

I've been having trouble placing it next to a fixed header; if said header has a `z-index` other than `auto`, a `top-*` toast shows up under it. Perhaps we could allow either `classNames` or `css` prop to be passed in to deal with custom positioning?

**Comment by JayV30** [comment]
Just from a quick look at the components -- it appears this be accomplished by just destructruring {...rest} as a prop in ToastContainer and then applying ...rest to the returned div? Then we could pass in style, className, etc... Or am I missing something?

Unfortunately don't currently have time to test and submit a pull request. Would this even be an appropriate solution?

**Comment by vcanales** [comment]
> Would this even be an appropriate solution?

Exactly my concern, I'd like to get @jossmac's input. I have time for a PR if this is an acceptable solution.

**Comment by sdubrez** [comment]
Any updates ?

**Comment by effectiveduck** [comment]
Had this same issue, in the end we just replaced the ToastContainer with one with the styles we needed.

`<ToastProvider components={{ ToastContainer }}>`

Definitely not ideal but works for now.

**Comment by crazyrobbin** [comment]
Change the css of class 
> .css-1p3cd4g
add margin-top:50px;
It will work now

**Comment by vcanales** [comment]
This is not sustainable, as the hash on the class would change between versions of the lib.

**Comment by jossmac** [comment]
> Had this same issue, in the end we just replaced the ToastContainer with one with the styles we needed.

Cheers @effectiveduck, that's the way to do it!

> Definitely not ideal but works for now.

Oh, that's not good 😞

* * *

How about a `placementOffset` property on the provider? It could be a tuple that reflects the `placement` coordinates. A value of `[200, 10]` and a placement of `top-right` would apply a 200px offset to the top, and a 10px offset to the right of the container. The second argument would likely be ignored for the `*-center` values.

```jsx
<ToastProvider placement="right" placementOffset={{ bottom }}>
  {/* your app*/}
</ToastProvider>
```

Thoughts?

**Comment by jossmac** [comment]
Alternatively I could put together styles API, similar to [what we've done for react-select](https://react-select.com/styles). This would also solve potential future issues, like z-index.

I think this is preferable. It would look something like:

```jsx
<ToastProvider styles={{
  container: (provided) => ({ ...provided, zIndex: 100, top: 50 }),
  toastContent: (provided, state) => ({ ...provided, padding: state.appearance === 'success' ? 15 : 10 }),
  toastIcon: () => ({ display: 'none' }),
}}>
  {/* your app */}
</ToastProvider>
```

**Comment by vcanales** [comment]
> Alternatively I could put together styles a API, similar to [what we've done for react-select](https://react-select.com/styles). This would also solve other issues, like z-index.

I would agree that this is the way to go.

**Comment by effectiveduck** [comment]
> Oh, that's not good 😞

Sorry I feel like I should clarify. We had to copy the default ToastContainer from the source (since we liked the default style), add the styles we needed (just z-index) and set it is as the new ToastContainer. It was a bit much just to apply a z-index, which is why...

> Alternatively I could put together styles a API, similar to what we've done for react-select. This would also solve other issues, like z-index.

Sounds great!

**Comment by jossmac** [comment]
_Cross posting from #39_

* * *

After refactoring a bunch of stuff and upgrading to emotion@10, the default toast container now accepts styles however you'd like to provide them:

```jsx
import { DefaultToastContainer } from "react-toast-notifications";

const ToastContainer = props => (
  <DefaultToastContainer
    className="toast-container"
    css={{ outline: "4px dashed green" }}
    style={{ background: "red" }}
    {...props}
  />
);
```

Checkout this CodeSandbox: https://codesandbox.io/s/toast-container-styles-duxs5

**Comment by duncan-iaria** [comment]
This solution worked out great for me, thank you!

**Comment by vcanales** [comment]
Perfect @jossmac, thank you!

**Comment by yale** [comment]
@jossmac This is great! However I think the Typescript types have not been updated to reflect this, so I'm getting a ts error when trying to use the `className` prop on the `DefaultToastContainer`:

```
Property 'className' does not exist on type 'IntrinsicAttributes & ToastContainerProps & { children?: ReactNode; }
```

I'm using `// @ts-ignore` right now to get around this.

**Comment by jossmac** [comment]
@yale if you'd like to submit a PR, I'll take a look at it.

**Comment by yale** [comment]
@jossmac Opened #93. Thank you!
