### ISSUE TITLE
My modal is overriding the react-toast-notifications notification pop-up

### ISSUE THREAD

**Issue by rafaelspaesleme-ads** [jossmac/react-toast-notifications#140]
I wonder if there is any solution to the problem attached.
When I activate the notification, within a modal, it appears behind the modal. See the image:

<img src='https://dev-my-blog.s3-sa-east-1.amazonaws.com/bug-do-milenio.png' alt='bug'/>

I would like to know if you could put something like, a position absolute, how do you use it in css to put an html tag in question, in full evidence?

I look forward to possible solutions.

**Comment by jossmac** [comment]
Please see issue #45

**Comment by rafaelspaesleme-ads** [comment]
Thank you!
