### ISSUE TITLE
Alternatives, for use with Redux

### ISSUE THREAD

**Issue by jossmac** [jossmac/react-toast-notifications#142]
- [Reapop](https://github.com/LouisBarranqueiro/reapop)
- [react-hot-toast](https://github.com/timolins/react-hot-toast) (i think)

**Comment by geekdaniels** [comment]
Great, I'll look into that. Thanks.

**Comment by shehi** [comment]
@jossmac , are there any plans to have Redux integration in this package as well? In my Next.js app, I wrapped my main component around `ToastProvider` and all of this went inside Redux's `Provider`, but problem is I keep getting this error:

![image](https://user-images.githubusercontent.com/653569/110821352-46d1fb00-8290-11eb-8598-2a38ace57078.png)

**Comment by jossmac** [comment]
@shehi No, there's no plans to integrate with Redux.

The `findDOMNode` warning is unrelated, see #82
