### ISSUE TITLE
Is there any example that how to use replaceable components?

### ISSUE THREAD

**Issue by huseynm** [jossmac/react-toast-notifications#146]
```
import { ToastProvider } from 'react-toast-notifications';

const MyCustomToast = ({ appearance, children }) => (
  <div style={{ background: appearance === 'error' ? 'red' : 'green' }}>
    {children}
  </div>
);

const App = () => (
  <ToastProvider components={{ Toast: MyCustomToast }}>...</ToastProvider>
);
```

**Comment by jossmac** [comment]
You could take a look at the [snack implementation](https://github.com/jossmac/react-toast-notifications/blob/master/examples/src/index.js#L35) from the example website, and where it's [passed to the provider](https://github.com/jossmac/react-toast-notifications/blob/master/examples/src/index.js#L251).
