### ISSUE TITLE
Still get scrollbars on exit animation

### ISSUE THREAD

**Issue by astralmedia** [jossmac/react-toast-notifications#149]
Using windows and chroma/brave, I am unable to get rid of the overflow scrollbars on the exit animation...any idea how to work around it? I just installed the library today, so it should be most recent.

Thanks for the awesome work!

**Comment by natashajaved** [comment]
Yeah please help out

**Comment by jossmac** [comment]
Should be resolved in `2.4.1`. Please let me know how you go
