### ISSUE TITLE
Bundle size is 184kb

### ISSUE THREAD

**Issue by fc** [jossmac/react-toast-notifications#15]
The dist directory is 184kb although I imagine it could be much smaller with optimizations.

Since you are already using webpack, you could use that so it can get minified (it uses uglify by default).

Additionally, you can use webpack visualizer to find any other potential optimizations:
https://chrisbateman.github.io/webpack-visualizer/

I got it down to 116KB with this generic webpack config:
```
const webpack = require('webpack');

module.exports = {
  mode: 'production',
  entry: './src/index.js',
  output: {
    path: __dirname + "/dist",
    filename: 'index.js',
    libraryTarget: 'umd',
    library: 'ReactToastNotifications'
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader'
      },
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader'],
      }
    ]
  },
  externals: [ 'react', 'react-dom' ],
  plugins: []
};
```

Generate a stats file for the webpack visualizer:
```
./node_modules/.bin/webpack --config webpack.prod.config.js --json > stats.json
```

react-transition-group, ToastElement and create-emotion appear to be the largest files bulk.

It looks like disabling `sourceMap` for emotion is not honored unless the node env is production...

```
NODE_ENV=production webpack --config webpack.prod.config.js
```

Got it down to around 56KB

**Comment by jossmac** [comment]
Hey, thanks for looking into this @fc

While those numbers look impressive, I'm not sure what the actual gain would be for doing this. What I mean is that it's not like you'd ship an app to production without minifying, right? This lib will just be part of your source.

I'd like to separate the styled components (emotion) out somehow, so if people are replacing them with their own, they don't pay for the additional cost. Though that should happen in the consumer build via tree-shaking...

Could potentially make emotion a `peerDependency`, then the cost is at least explicit and transparent.
