### ISSUE TITLE
React Warning: Unknown event handler property `onDismiss`. It will be ignored.

### ISSUE THREAD

**Issue by damngamerz** [jossmac/react-toast-notifications#153]
Possible problem.

This basically happens when you pass a prop with a name starting with on, regardless of its case. React assumes and tries to bind it with javascript events like onClick, onKeypress, etc
Ref: https://stackoverflow.com/a/63385318

I think renaming the onDismiss should work.

**Comment by jossmac** [comment]
Are you replacing the `Toast` component? It's likely that you're spreading `onDismiss` onto a DOM element.
