### ISSUE TITLE
 addToast not accessible while calling on render without an event click  

### ISSUE THREAD

**Issue by alamm9456** [jossmac/react-toast-notifications#160]
addToast not accessible while calling on render without an event click  ,
To use the addToast method we need to call this on an event click like onSubmit, onClick.

addToast should also be accessible when i am just rendering it on conditional basisc

**Comment by jossmac** [comment]
@alamm9456 Please provide a reproduction of the bug, or at the very least a snippet of the offending code. Without this I cannot diagnose the problem and will have to close the issue.
