### ISSUE TITLE
Cross button on Toast doesn't work if custom ToastContainer is provided.

### ISSUE THREAD

**Issue by zkhil1** [jossmac/react-toast-notifications#167]
Reproducibility: 100%

Steps to reproduce:
1. Implement a simple ToastContainer
2. Provide this to the ToastProvider.
3. Trigger a Toast and try to click on the cross icon to dismiss. It doesn't work, in fact the mouse cursor is not changed to pointer either.

https://codesandbox.io/s/interesting-wave-ssvjs?file=/src/App.js:523-637

**Comment by jossmac** [comment]
You have declared `pointerEvents: 'none'` [on the container](https://codesandbox.io/s/interesting-wave-ssvjs?file=/src/App.js:321-350), this declaration is [inherited](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events#formal_definition).
