### ISSUE TITLE
adjusting the height

### ISSUE THREAD

**Issue by hassanzadeh** [jossmac/react-toast-notifications#168]
Hey,
I wonder if it is possible to adjust the height of toasts. My toast messages are one liners but it looks like the height is set for 2 lines.
THanks

**Comment by mostafa-rahmani** [comment]
Hey @hassanzadeh.
For adjusting the height you can easily create a global CSS file and overwrite the styles for the toast class. The toast CSS class is currently react-toast-notifications__toast__content. inspect the element for the exact class name.
then add CSS file into your app.js file

**Comment by hassanzadeh** [comment]
Thanks Mostafa.
