### ISSUE TITLE
Export ToastContainer and DefaultToast

### ISSUE THREAD

**Issue by fc** [jossmac/react-toast-notifications#17]
Rather then creating a complete replacement of the default toast component I would rather be able to do something like this:

MyToast.js
```
import { DefaultToast } from 'react-toast-notifications';
export ({children, ...props}) => <DefaultToast {...props}><SomethingSpecial>{children}</SomethingSpecial></DefaultToast>;
```

**Comment by fc** [comment]
I did make a pr, it is linked in this thread.

**Comment by jossmac** [comment]
Ugh, sorry mate. Thank you for that,!
