### ISSUE TITLE
Set a max number of Toasts to be open

### ISSUE THREAD

**Issue by nuel77** [jossmac/react-toast-notifications#175]
A prop which takes the maximum number of toasts that is shown at a time can be really helpful to remove some clutter.

**Comment by jossmac** [comment]
I think this could be potentially harmful, and **do not** recommend it. The stack could max-out at an arbitrary number stopping the user from seeing an important notification.

With that said, you can implement this yourself. It'd look something like:

```js
import { useToasts as useToastsOriginal } from 'react-toast-notifications'

const MAX_TOASTS = 10

export function useToasts() {
  const { addToast: addToastOriginal, removeToast, removeAllToasts, updateToast, toastStack } = useToastsOriginal()
  
  // augment the method however you like
  const addToast = (...args) => {
    if (toastStack.length < MAX_TOASTS) {
      return addToastOriginal(...args);
    }
  }

  return { addToast, removeToast, removeAllToasts, updateToast, toastStack }
}
```
