### ISSUE TITLE
Support new Hook system

### ISSUE THREAD

**Issue by MBach** [jossmac/react-toast-notifications#20]
Hi,
Thank you for this very useful library. Do you plan to support hooks in the future? I'm writing an App which uses both classes and hooks, and I have to do some "props drilling" when I want to display a toast sometimes (in Hook functions).

https://reactjs.org/docs/hooks-overview.html

Like:
```
class MyAwesomeClass extends Component {
  render() {
    const { toastManager } = this.props
    return (<>
      <SomeOtherClass />
      <MyHook toastManager={toastManager} />
    </>)
  }
}
export default withToastManager(withUser(withRouter(withStyles(styles, { withTheme: true })(MyAwesomeClass ))))
```

**Comment by jossmac** [comment]
Yeah, I spiked that a while ago -- you can check out the [CodeSandbox](https://codesandbox.io/s/71q1xvjnx).

I'm pretty time poor at the moment, so I probably won't get around to the full implementation in the near future. A PR would be very welcome 🙂

**Comment by nagey** [comment]
any update on when we might expect this in the main package? Thanks, love this implementation of toasts!
