### ISSUE TITLE
onDismiss overrides default onDismiss behaviour

### ISSUE THREAD

**Issue by LMulvey** [jossmac/react-toast-notifications#21]
**Expected Result**
Passing in the `onDismiss` function would be treated as a "EventHook" fired when the toast is removed/dismissed allowing us to modify external state, i.e, change a route or fire off an analytics event.

**Actual Result**
When passing the `onDismiss` prop/option to a `toastManager.add` call, the passed-in prop overrides the internal behaviour entirely. 

This may very well have been your intent here and while this doesn't work for my use case, perhaps there are edge cases that I'm not thinking of. Based on your docs in the README though, I feel that this is a bug. Happy to submit a PR if that is the case 😄

**Comment by LMulvey** [comment]
That is exactly the case! I'll work on it over the next little while and get a PR in 😄

**Comment by shadialtarsha** [comment]
Hello,
Any workaround for dismissing the toast pragmatically?

**Comment by LMulvey** [comment]
@shadialtarsha  - this issue and the PR I'm going to submit basically fires your `onDismiss` prop _before_ firing the internal one. It could be used for firing analytics services when a toast is dismissed–stuff like that. 

To achieve what you'd want to do, you'd have to use the callback provided by the `ToastManager.add` function - `add(content, options, cb)`  which receives the toastId as a parameter. If you save that toastId to state (or somewhere), you could make your _own_ function that calls `ToastManager.remove` with the previously-saved toastId.
