### ISSUE TITLE
Publish latest version to npm

### ISSUE THREAD

**Issue by ashwhall** [jossmac/react-toast-notifications#26]
The version on npm is from 5 months ago, and doesn't have the changes from #17 
Can the new version please be pushed to npm?

**Comment by ashwhall** [comment]
@jossmac Can you please do this? I'd really like to use `DefaultToast`

**Comment by GCDeveloper** [comment]
Same

**Comment by ChrisLincoln** [comment]
Yep.

**Comment by jossmac** [comment]
Sorry about that. Sorted in latest.
