### ISSUE TITLE
DefaultToast not exported?

### ISSUE THREAD

**Issue by blumendorf** [jossmac/react-toast-notifications#27]
There seems to be an issue with DefaultToast in the latest version.

```
import { DefaultToast } from 'react-toast-notifications';
console.log(DefaultToast) // -> undefined
```

**Comment by ashwhall** [comment]
I believe this is due to the latest version not being pushed to npm. Same problem as issue #26

**Comment by jossmac** [comment]
Sorry about that. Sorted in latest.
