### ISSUE TITLE
Is it possible to add audio?

### ISSUE THREAD

**Issue by spyshower** [jossmac/react-toast-notifications#28]
I think it would be really cool if we could play audio as well (optionally).

**Comment by jossmac** [comment]
The `add` method takes a callback:

```jsx
toastManager.add(`Success`, { appearance: 'success' }, () => {
  // play sound
});
```

Maybe checkout the [Web Audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API).
