### ISSUE TITLE
autoDismiss needs to be set to true

### ISSUE THREAD

**Issue by richmilton** [jossmac/react-toast-notifications#35]
May be an omission in readme or a quirk in my app - I had to set autoDismiss prop to true in ToastProvider wrapper to get timeout to work (prop only mentioned in readme for Toast component). Thanks for lib! Hope this is useful.

**Comment by CraigInBrisbane** [comment]
I second this request. I was wondering why mine was staying until I clicked close. I'd suggest the same default for autoDismiss.

**Comment by jossmac** [comment]
@richmilton @CraigInBrisbane  you must set the `autoDismiss` property in the config of each `add` call. The `ToastProvider` is only for common config like `autoDismissTimeout`.

If you're suggesting a bug where `autoDismiss` is only observed when passed to the provider could you please provide a reproduction in [CodeSandbox](https://codesandbox.io)?
