### ISSUE TITLE
Custom ToastContainer component not functioning as expected

### ISSUE THREAD

**Issue by ConnorTCM** [jossmac/react-toast-notifications#39]
As seems to be the case with a few people, I'm struggling to style the ToastContainer. After reading the docs and [this issue](https://github.com/jossmac/react-toast-notifications/issues/14) I was under the impression that I could provide a custom ToastContainer component which I have done, but the issue I have now is that when triggering a notification the toast container isn't populated. If I don't pass my custom container to the `components` prop on the ToastProvider then the toast is populated. Is there something I'm not passing down from the ToastProvider to the ToastContainer?

Also worth noting I tried to customise the existing component in the same way the docs do with the Toast component to no avail.
```
import { DefaultToastContainer } from 'react-toast-notifications';
```

Any pointers would be much appreciated!

_app.js
```
import App, { Container } from "next/app";
import React from "react";
import { ToastProvider } from "react-toast-notifications";

import ToastContainer from "../components/notifications/toastContainer";
import Toast from "../components/notifications/toast";

class MyApp extends App {
  render() {
    const { Component, pageProps } = this.props;

    return (
      <Container>
        <ToastProvider components={{ ToastContainer, Toast }}>
          <Component {...pageProps} />
        </ToastProvider>
      </Container>
    );
  }
}

export default MyApp;
```

ToastContainer.js
```
import React from "react";
import styled from "styled-components";

const Root = styled.div`
  position: fixed;
  top: 20px;
  left: 50%;
  transform: translateX(-50%);
  z-index: 20;
`;

const ToastContainer = ({ children, ...rest }) => {
  return <Root {...rest}>{children}</Root>;
};

export default ToastContainer;
```

**Comment by MarkLyck** [comment]
Have the same issue :/

**Comment by nate456789** [comment]
I would just like to move it from the default position of upper right and I am have zero luck.
If anyone has and example code that would be nice

**Comment by priteshjha4u** [comment]
@MarkLyck 
In this lib (see docs), they have given flexibility to override `Toast` component, not the `ToastContainer`. Although technically we can override this also, as you are trying to do (not recommended). your code is not working because you are missing few important things in your custom `ToastContainer` component, here is is modified version of your `ToastContainer` component which should work.
```javascript
import React from 'react';
import styled from 'styled-components';
import { TransitionGroup } from 'react-transition-group';

const Root = styled.div`
  position: fixed;
  top: 20px;
  left: 50%;
  height: 100%;
  maxheight: 100%;
  overflowx: hidden;
  overflowy: auto;
  transform: translateX(-50%);
  z-index: 20;
  padding: 10px;
`;

const ToastContainer = ({ children, placement, ...rest }) => {
  return (
    <Root {...rest}>
      <TransitionGroup component={null}>{children}</TransitionGroup>
    </Root>
  );
};

export default ToastContainer;
```

**Comment by jossmac** [comment]
@nate456789 please [the documentation](https://github.com/jossmac/react-toast-notifications#toastprovider-props) for `placement`.

**Comment by jossmac** [comment]
@ConnorTCM @MarkLyck after refactoring a bunch of stuff and upgrading to emotion@10, the default toast container now accepts styles however you'd like to provide them:

```jsx
import { DefaultToastContainer } from "react-toast-notifications";

const ToastContainer = props => (
  <DefaultToastContainer
    className="toast-container"
    css={{ outline: "4px dashed green" }}
    style={{ background: "red" }}
    {...props}
  />
);
```

Checkout this CodeSandbox: https://codesandbox.io/s/toast-container-styles-duxs5

* * *

I'm afraid I can't afford the time right now to implement the solution described in #14, but I think this will be sufficient for most instances.

**Comment by jossmac** [comment]
Thank you for your response @priteshjha4u, that would have worked. Since refactoring, the consumer no-longer needs to understand  or implement "react-transition-group".

**Comment by citypaul** [comment]
People in this thread may find the solution I came up with here useful. It's working for me: https://github.com/jossmac/react-toast-notifications/issues/44
