### ISSUE TITLE
Expose toast manager outside components scope.

### ISSUE THREAD

**Issue by priteshjha4u** [jossmac/react-toast-notifications#40]
Hi,

This is not an issue rather could be an enhancement. correct me if i am wrong, currently we can add toasts only inside a react component decorated with `withToastManager` (or using render props), which expose a prop `toastManager` in the given component. but sometimes we have a requirement to add toasts outside a react component/classes, for example, in a redux action, some service class, or any custom class for that matter. recently i had a requirement like this so i did a simple work around to achive this functionalty, please let me know if this is fine and legitimate thing to do, here is my changes

in `ToastProvider.js`
```javascript
// expose an object to contain references of  add, remove methods
export const ToastManager = {};

// attach the reference here
constructor(props: Props) {
    super(props);
    this.cacheComponents(props.components);
    this.state = { toasts: [] };
    ToastManager.add = this.add;
    ToastManager.remove = this.remove;
  }
```

in `index.js`
```javascript
export { ToastContainer as DefaultToastContainer } from './ToastContainer';
export { DefaultToast } from './ToastElement';
export {
  ToastConsumer,
  ToastProvider,
  withToastManager,
  ToastManager // newly exposed API
} from './ToastProvider';
```

**Comment by jossmac** [comment]
Hi @priteshjha4u,

I think that if a consumer needs to access toast methods outside of a react component then they should own the abstraction. I won't have enough context to create the right solution.

**Comment by Emnalyeriar** [comment]
Hey @jossmac 
I have a use case that might be related to this issue.
Is it possible to somehow addToast outside of components? With react hooks it can only be used inside a body of a function component.
In my case - I would like to display a toast from my axios error handler which is a separate utility function.

**Comment by cinnabarcaracal** [comment]
This project looks great but we cannot use it with our saga based architecture. It is not uncommon to use react in a way where components are thin (without much if any logic) while redux sagas (or thunks) handle the actual side effects of things like button presses. Exposing toast management functions so that they can be used in this way would open this project up to more people.

**Comment by jossmac** [comment]
The implementation relies on context, so anything outside of the provider's tree won't have access.

Please see [alternatives](https://github.com/jossmac/react-toast-notifications#alternatives) or perhaps [npm](https://www.npmjs.com/search?q=keywords:toast).

**Comment by cinnabarcaracal** [comment]
Not an implementation suggestion, but a potential workaround for anyone who needs to use this in their sagas and is willing to use a bit of a hack:

```
// index.js

// ...

window.__react_toast_provider = React.createRef();

ReactDOM.render(
  <Provider store={store}>
    <ToastProvider ref={window.__react_toast_provider}>
      <Router history={history}>
        <Route component={App} />
      </Router>
    </ToastProvider>
  </Provider>,
  document.getElementById('root'),
);

// ...
```

```
// someSaga.js

// lodash is not required, but `get` makes this easier to read
import lodash from 'lodash';

export default function () {
  const addToast = lodash.get(window, '__react_toast_provider.current.add');

  if (addToast) {
    addToast('foo', {
      appearance: 'success',
      autoDismiss: true,
      pauseOnHover: false,
    });
  }
}

```

It works by adding a ref for the `ToastProvider` to the global `window` object, which you can then access from anywhere that has access to `window`.

**Comment by jossmac** [comment]
This is nice @cinnabarcaracal, it's important for consumer's to own their abstraction. You could take that a little bit further to improve DX:

```js
export function addToast(...args) {
  const add = lodash.get(window, '__react_toast_provider.current.add')

  if (!add) {
    console.error('Some helpful error.')
    return
  }

  add(...args)
}

// somewhere else in your app

import { addToast } from '../abstraction'

addToast('content', {/* options */})
```

**Comment by Emnalyeriar** [comment]
This isn't the most elegant solution but I created a Smart ToastContainer that listens for specific redux actions that are emited on http errors:
```
function Layout({
  children,
  isLoggedIn,
  pathname,
}) {
  return (
    <ToastProvider
      placement="bottom-right"
    >
      <ToastContainer />
      .......
    </ToastProvider>
  );
}
```
```
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import PropTypes from 'prop-types';

import { useToasts } from 'react-toast-notifications';

import { uiSelectors } from '@store/selectors/ui';

function ToastContainer({
  activeToast,
}) {
  const { addToast } = useToasts();

  useEffect(() => {
    if (activeToast.text) {
      addToast(activeToast.text, {
        appearance: 'error',
        autoDismiss: true,
        ...activeToast.options,
      });
    }
  }, [activeToast]);

  return <React.Fragment />;
}

ToastContainer.propTypes = {
  activeToast: PropTypes.shape({
    options: PropTypes.shape({}),
    text: PropTypes.string.isRequired,
  }).isRequired,
};

const mapStateToProps = state => ({
  activeToast: uiSelectors.activeToast(state),
});

export default connect(
  mapStateToProps
)(ToastContainer);
```
```
    window.store.request.onErrorCallbacks.push((error) => {
      window.store.dispatch(showToast({
        options: {},
        text: 'Something went wrong!',
      }));
    });
```

**Comment by jossmac** [comment]
Ref #142

**Comment by alisternorris** [comment]
https://github.com/alisternorris/react-outside-call
