### ISSUE TITLE
Allow consumers to inject any React Component as a toast in the add function

### ISSUE THREAD

**Issue by citypaul** [jossmac/react-toast-notifications#44]
Hello there,

Thanks for your great work on this library.

I've spent some time in work looking into what is currently out there in React world regarding toast components. I looked into quite a few of them, but none of them appeared to quite work for what I needed.

I am working with components built as part of a design system, so I really want to be able to just use a component I already have. The hard part of toast notifications is the managing of the toasts themselves, which is what your `<ToastProvider/>` component takes care of. 

So ideally, I was looking for an API that might look something like this:

```jsx
<ToastConsumer>
{
  ({add}) => {
    add(<MyCustomComponent />, {options...})
  }
}
</ToastConsumer>
```
Where the provider would still take care of managing the toast functionality, handling the timing of them and all that stuff, but crucially, I can pass any component in to the `add` function itself, not just into the `<ToastProvider/>`. The reason I want to be able to do this is because we have a component library in work with existing components, and being able to inject them in to the `add` function feels a lot more powerful than having a single component injected into the provider itself.

Anyway, using your library, I managed to get this to work for my needs without touching the inside of your code at all, and this seems much more flexible.

I created a HOC to populate any component with the props your setup needs (so creating props for `onMouseEnter` and `onMouseLeave` etc, and instead of using `children` as text, I created a custom component that looks like this:

```jsx

const MyCustomToast = ({ children, ...rest }) => {
 // here, instead of expecting children to be text, we treat children like a react component
// we therefore need to pass the rest of the props that come from your provider onto the react component itself...
return (
    <Fragment>
      {React.Children.map(children, child => {
        return React.cloneElement(child, { ...rest })
      })}
    </Fragment>
  )
}

const withToastProps = Component => ({ onMouseEnter, onMouseLeave, ...rest }) => (
  <div onMouseEnter={onMouseEnter} onMouseLeave={onMouseLeave}>
    <Component {...rest} />
  </div>
)
```

So usage looks like:

```jsx
<ToastConsumer>
{({ add }) => {
  const ToastableFeedbackBlock = withToastProps(FeedbackBlock)

  return (
    <Fragment>
      <Button
        onClick={e => {
          add(
            <ToastableFeedbackBlock
              headerText="Something good"
              bodyText="Something good just happened yada yada yada"
              success
              dismissable
            />,
            { autoDismiss: true, pauseOnHover: true, placement: "top-center" },
          )
        }}
      >
        Render success toast
      </Button>
    </Fragment>
  )
}}
</ToastConsumer>
```

This works nicely for my needs, and it means that I can inject anything in as a toast, and your `<ToastProvider/>`  just manages it for me.

I wondered if you might be interested in me sticking a pull request in for you that makes this possible as part of the core library? I was thinking you could have a check in the first parameter of the `add` method, so if you pass in a React Component, it’ll enable the above scenario. 

This would mean anyone could use your `<ToastProvider>` to manage their own components.

Please let me know what you think.

**Comment by citypaul** [comment]
I'd be happy to look into this myself and perhaps issue a PR if you agree there's value in it. So long as we can agree on what the end API should look like. Let me know if you'd be interested in this.

**Comment by jossmac** [comment]
Hi @citypaul,

I think that you may have misunderstood the API. What you're suggesting above can be achieved with the current implementation. You would pass your component as the `Toast` to the provider:

```jsx
<ToastProvider components={{ Toast: ToastableFeedbackBlock }}>
  ...
</ToastProvider>
```

The toast component is passed all config as props, so you can do whatever you want inside `ToastableFeedbackBlock`.

```jsx
const { addToast } = useToasts();

addToast('you could also map `content` to `bodyText', {
  headerText: "Something good",
  bodyText: "Something good just happened yada yada yada",
  success: true,
  dismissable: true,
  autoDismiss: true,
  pauseOnHover: true
});
```

**Comment by citypaul** [comment]
@jossmac thank you for your response.

It wasn't quite clear to me that the config props were all passed on to the toast component like this, so it may be worth updating your docs to mention this explicitly?

I do think however that the change I'm talking about still has some value.

The reason I still think it's nicer is because it allows the consumer to inject different React components to be used as a toast at run time, instead of having a single React component that has to know about every requirement.

I'm using this in my app now because I had a different use case - I already had a pre-existing `FeedbackBlock` component that has an api like this:

```jsx
<FeedbackBlock headerText="I am an error block" bodyText="I am some text content" error />
```

But you can also do:

```
<FeedbackBlock headerText="I am an error block" bodyText="I am some text content" success />
```

And so on, there's various options.

Using what you have here now, we'd have a single "Master" toast that would then need to know all the use cases for any toast in the system, and I imagine this could get complicated in some scenarios. It seemed to me to be far more flexible and easier to use if we could just pass a React component in as the first parameter. That way you retain flexibility without having to create a master component that needs to know about the whole world.

For the record, here's the entirety of what I've done to make this work for me:

```tsx
import React, { Fragment, ReactNode, ReactElement } from "react"
import { ToastProvider as ReactToastProvider, ToastConsumer as ReactToastConsumer } from "react-toast-notifications"
import { FeedbackBlock } from "@freshfields/react-component-library"

interface ToastProvider {
  /** Determines the placement of toasts.
   * @default "top-right"
   */
  placement?: "bottom-left" | "bottom-center" | "bottom-right" | "top-left" | "top-center" | "top-right"
  /** Any react component */
  children: ReactNode
}

interface AddOptions {
  /**
   * Whether or not to dismiss the toast automatically after a timeout.
   *
   * @default false
   */
  autoDismiss?: boolean
  /**
   * The amount of time in milliseconds the autoDismiss will wait for if it is set to true
   *
   * @default 5000
   */
  autoDismissTimeout?: number
  /**
   * Whether or not to pause the timeout when the user hovers over the toast element
   *
   * @default false
   */
  pauseOnHover?: boolean
}

interface ToastConsumerProps {
  add: (children: ReactElement, {  }: AddOptions) => null
}

interface ToastConsumer {
  children(props: ToastConsumerProps): JSX.Element
}

interface AllowAnyComponentProps {
  children: ReactElement
}

interface WithToastPropsProps {
  Component: ReactElement
}

const AllowAnyComponentAsToast = ({ children, ...rest }: AllowAnyComponentProps) => (
  <Fragment>{React.Children.map(children, child => React.cloneElement(child, { ...rest }))}</Fragment>
)

export const withToastProps = (Component: WithToastPropsProps) => ({ onMouseEnter, onMouseLeave, ...rest }: any) => (
  <div onMouseEnter={onMouseEnter} onMouseLeave={onMouseLeave}>
    <Component {...rest} />
  </div>
)

export const ToastProvider = ({ children, ...rest }: ToastProvider) => (
  <ReactToastProvider components={{ Toast: AllowAnyComponentAsToast }} {...rest}>
    {children}
  </ReactToastProvider>
)

export const ToastConsumer = (props: ToastConsumer) => <ReactToastConsumer {...props} />
export const ToastableFeedbackBlock = withToastProps(FeedbackBlock)


```
