### ISSUE TITLE
How to make ToastContainer in top of all other components?

### ISSUE THREAD

**Issue by iamwmude** [jossmac/react-toast-notifications#45]
Hi, I need to place the toast as top of all other components, there's only one way that modify css of source code, does it okay to access outer style to modify toast style?

**Comment by iamwmude** [comment]
Hi, I need to place the toast as top of all other components, there's only one way that modify css of source code, does it okay to access outer style to modify toast style?

**Comment by jossmac** [comment]
You can replace the toast container:

```jsx
import { DefaultToastContainer } from 'react-toast-notifications';

export const MyCustomToastContainer = props => (
  <DefaultToastContainer {...props} style={{ zIndex: 9999 }} />
);

// wherever you render the provider pass the new component

<ToastProvider components={{ ToastContainer: MyCustomToastContainer }}>
...
</ToastProvider>
```
