### ISSUE TITLE
Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by raynox** [jossmac/react-toast-notifications#46]
Hi, I tried to use `useToasts` hook in Next.js but I get following error: `Cannot read property 'add' of undefined`, do you have any idea what is wrong with my code?

```jsx
import {useToasts} from 'react-toast-notifications';
import api from '../api';

export default () => {

    const { addToast, removeToast, toastStack } = useToasts();
    const [name, setName] = useState(null);
    const [email, setEmail] = useState(null);
    const [password, setPassword] = useState(null);

    const registerUser = () => {
        return api.post('api/users', {name, email, password})
            .then(() => addToast('User was registered!', {
                appearance: 'error',
                autoDismiss: true,
                pauseOnHover: true,
            }))
            .catch(() => alert('Could not register user!'));
    };

//...
```

**Comment by bntzio** [comment]
Yeah I'm having the same issue as well, will look further into it later in the day.

**Comment by jossmac** [comment]
@raynox @bntzio thanks for letting me know. Could I could get some more info:

- which version of "react-toast-notifications" are you using?
- @bntzio are you also using Next.js, or some other SSR solution?

Would love a reproduction. I've tried sym-linking, but end up with the "[two versions of react](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react)" issue.

**Comment by bntzio** [comment]
@jossmac I'm not using next, just CRA, using `react-toast-notifications` v2.2.1.

I've tried with the hooks version as well as with the HOC provider one.

**Comment by lapongua** [comment]
I solved wrapping the component with <ToastProvider>

```
import { ToastProvider, useToasts } from 'react-toast-notifications'
 
const FormWithToasts = () => {
  const { addToast } = useToasts()
 
  const onSubmit = async value => {
    const { error } = await dataPersistenceLayer(value)
 
    if (error) {
      addToast(error.message, { appearance: 'error' })
    } else {
      addToast('Saved Successfully', { appearance: 'success' })
    }
  }
 
  return <form onSubmit={onSubmit}>...</form>
}
 
const App = () => (
  <ToastProvider>
    <FormWithToasts />
  </ToastProvider>
)
```

**Comment by jossmac** [comment]
@lapongua cheers mate! That's the solution.

To avoid this confusion in the future, i've added an error so the hook will now throw if it can't find its provider. You'll see something like:

```
Error: The `useToasts` hook must be called from a descendent of the `ToastProvider`.
```

**Comment by agrohs** [comment]
What commit/PR was this update made in??
