### ISSUE TITLE
Replace deprecated lifecycle method

### ISSUE THREAD

**Issue by jcmnunes** [jossmac/react-toast-notifications#50]
ToastProvider is using a deprecated lifecycle method (`componentWillReceiveProps`).
In React 17.x, only the UNSAFE_ name will work.

Consider renaming the method or use `componentDidUpdate` instead.

**Comment by citypaul** [comment]
For a bit more context, the recent release of React `16.9.0` is causing the above error to be output in the console.

**Comment by jossmac** [comment]
@jcmnunes @citypaul I'm pretty busy at the moment, but happy to review your PR.

**Comment by jcmnunes** [comment]
> @jcmnunes @citypaul I'm pretty busy at the moment, but happy to review your PR.

Sure, I can have a look at that.
