### ISSUE TITLE
Add a link in the toast message

### ISSUE THREAD

**Issue by anz000** [jossmac/react-toast-notifications#51]
As the title suggests, I want to add a link in a toast message.

For instance, 
Looks-like: Please click here
Actual : Please click <a href="xyz> here </a>

And then the click on the link would go to the link. 

What would be the easiest way to do this? Thanks.

**Comment by jossmac** [comment]
The [content of the toast accepts `$React.Node`](https://github.com/jossmac/react-toast-notifications#hook), which is often just a string.

```jsx
const { addToast } = useToasts()

addToast(<div>Please click <a href="xyz"> here</div>, {/* your options */})
```

**Comment by jossmac** [comment]
@anz000 you may have to roll back to `<=1.5.0`, before hooks were introduced. Or upgrade your app's React dependency to `>16.8.0` (when hooks were introduced).

**Comment by anz000** [comment]
Just wanted to point out that neither works with toastManager.
