### ISSUE TITLE
Scroll bar appears on exit animation

### ISSUE THREAD

**Issue by jehugaleahsa** [jossmac/react-toast-notifications#52]
I'm noticing on Firefox and Chrome that a scrollbar appears momentarily during the exit animation. It's minor and barely noticeable, but probably worth pointing out anyway.

**Comment by jossmac** [comment]
@jehugaleahsa are you on windows?

This is difficult for me to test, but I'd be happy to take a look at a PR.

**Comment by jehugaleahsa** [comment]
I honestly I'll just close the ticket. The project I'm working on has some pretty nasty components and I guarantee they're the real problem. Mysterious CSS issues abound.

**Comment by jossmac** [comment]
Okay mate, if you need it re-opened just ping this thread with whatever you've discovered.

**Comment by eberkund** [comment]
I am also having this issue (on Windows)

**Comment by jossmac** [comment]
@eberkund difficult for me to test/address for Windows. Happy to look at a PR.

**Comment by minimaluminium** [comment]
@jossmac It's also reproducible on a Mac by selecting `Always` in `General > Show scroll bars` in System Preferences. Here is [a little screencast](https://www.dropbox.com/s/dxf2xhrs4wjpsgy/react%20toast%20scrollbar%20issue.mov?dl=0).
