### ISSUE TITLE
add placement to hook

### ISSUE THREAD

**Issue by tafelito** [jossmac/react-toast-notifications#53]
placement option doesn't seem to be working when using addToast hook. It does work if is set in the provider

**Comment by jossmac** [comment]
That's correct, `placement` is [inherited from the provider](https://github.com/jossmac/react-toast-notifications#toast-props).

**Comment by tafelito** [comment]
What if I don't want to use a custom Toast but I do want a different placement per notification?

**Comment by jossmac** [comment]
> but I do want a different placement per notification

That sounds strange. Could you give me some more context?

**Comment by tafelito** [comment]
Let's say to simplify,  I have 2 types of messages, an error message and a success message. I want the error to be shown centered at the top of the screen and the success at the bottom right of the screen. So in that case I would want to set the placement in the addToast call

**Comment by jossmac** [comment]
Sorry @tafelito, I don't think I can support that in a graceful way.

Please see [alternatives](https://github.com/jossmac/react-toast-notifications#alternatives) or perhaps [npm](https://www.npmjs.com/search?q=keywords:toast).
