### ISSUE TITLE
toast instance not returned on add (withToastManager)

### ISSUE THREAD

**Issue by ajshres** [jossmac/react-toast-notifications#56]
Hi,
I was testing remove toast withToastManager but could not remove it. On further investigations, the add method does not return anything at all.

https://github.com/jossmac/react-toast-notifications/blob/master/src/ToastProvider.js#L84

I checked the code and the return statement for add is within another function, making the main function return nothing. Could you please at least return id so remove could work?

**Comment by jossmac** [comment]
Hi @ajshres,

You can use the [third argument](https://github.com/jossmac/react-toast-notifications#hook) to `add` [which is a callback](https://github.com/jossmac/react-toast-notifications/blob/master/src/ToastProvider.js#L85) taking the `id` as it's only argument.

Returning the `id` from add might be a nice API, I'll have to see how that works with `setState` which is async. Will post here if that changes.

**Comment by ajshres** [comment]
Thanks @jossmac  this should work for now.
Will it work if you just return the id after the async setState. It should not actually affect any of the async nature of the function.

```
add = (content: Node, options?: Options = {}, cb: Callback = NOOP) => {
    const id = generateUEID();
    const callback = () => cb(id);

    this.setState(state => {
      const toasts = state.toasts.slice(0);
      const toast = Object.assign({}, { content, id }, options);

      toasts.push(toast);

      return { toasts };
    }, callback);
   return id;
  };
```
What do you think of it? Please let me know as well. Should not have much issue with this hack.

**Comment by jossmac** [comment]
Closing in favour of #48 

Please see [my comment](https://github.com/jossmac/react-toast-notifications/issues/48#issuecomment-519751525) regarding consumer controlled IDs.

**Comment by jossmac** [comment]
@ajshres the generated id is returned from the add method in #77
