### ISSUE TITLE
Not able to import 

### ISSUE THREAD

**Issue by pavanmurapala** [jossmac/react-toast-notifications#58]
Could not find a declaration file for module 'react-toast-notifications'. 'c:/Users/pmurapala/Desktop/04-08-2019/frontend/node_modules/react-toast-notifications/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-toast-notifications` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-toast-notifications';`ts(7016)
Could not find a declaration file for module 'react-toast-notifications'. 'c:/Users/pmurapala/Desktop/04-08-2019/frontend/node_modules/react-toast-notifications/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-toast-notifications` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-toast-notifications';`ts(7016)
Could not find a declaration file for module 'react-toast-notifications'. 'c:/Users/pmurapala/Desktop/04-08-2019/frontend/node_modules/react-toast-notifications/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-toast-notifications` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-toast-notifications';`

**Comment by elfico** [comment]
You beat me to it. Just trying out this library now and I got the same error.

**Comment by pavanmurapala** [comment]
I think it wont work for react .JS files or what . I am not sure..  Need help team.

**Comment by lukahartwig** [comment]
Your using this library in a typescript project but it doesn't have typescript declarations. You can either set the `noImplicitAny` in your `tsconfig.json` to `false` or follow the error message and add a declaration file somewhere in your project like this.

```ts
// react-toast-notifications.d.ts
declare module 'react-toast-notifications';
```

**Comment by jossmac** [comment]
This is not a TypeScript library. If someone would like to expose types pull requests are welcome.

**Comment by jossmac** [comment]
Please see #24, specifically [this comment](https://github.com/jossmac/react-toast-notifications/issues/24#issuecomment-550502984) for a DefinitelyTyped solution.
