### ISSUE TITLE
Adding custom css property to toast container

### ISSUE THREAD

**Issue by PJijin** [jossmac/react-toast-notifications#60]
I just want to adjust the z-index of the toast container. At now user fills data insides the modal box and the toast is not appearing properly. I am using useToasts() hook.

**Comment by shrijan00003** [comment]
having same issue, using with material-ui , toast appears beside the modal box.

**Comment by nermand** [comment]
@PJijin  Exploring solutions for myself as well. 
It seems this would work for your use-case: https://github.com/jossmac/react-toast-notifications/issues/45#issuecomment-515818086

**Comment by PJijin** [comment]
@nermand  That works 🙌🏻🎉
