### ISSUE TITLE
autoDismissTimeout doesn't auto dismiss 

### ISSUE THREAD

**Issue by deantheiceman** [jossmac/react-toast-notifications#61]
I'm using the ToastProvider and hooks

```
<ToastProvider placement='bottom-right' autoDismissTimeout={400}>
          <Component {...pageProps} />
        </ToastProvider>
```

```
const { addToast } = useToasts()

if (errorB) addToast('Error connecting to server', { appearance: 'error' })
```

My toast doesn't disappear automatically. Any ideas?

**Comment by zouhenry** [comment]
```autoDismissTimeout={400}``` from ```<ToastProvider>``` won't dismiss your toasts. You'll still need to specify ```{autoDismiss:true}``` on each instance of ```addToast```.

```
 addToast('Error connecting to server!', { appearance: 'error', autoDismiss: true })}
```

**Comment by jossmac** [comment]
@deantheiceman please see [my response](https://github.com/jossmac/react-toast-notifications/issues/66#issuecomment-557458007) to #66 

Closing this for now, but I am considering inheritance of the `autoDismiss` property.

**Comment by jossmac** [comment]
The `autoDismiss` property will be inherited from the provider since `2.3.0`
