### ISSUE TITLE
Redux Implementation

### ISSUE THREAD

**Issue by geekdaniels** [jossmac/react-toast-notifications#63]
Hi, I really love your library it's superb but i am finding it hard to use, can you kindly give me some insights on how I would implement with redux. Thanks a bunch.

**Comment by jossmac** [comment]
Hi @geekdaniels, thank you for the kind words.

I think you're talking about access to the toast store outside of the react tree. Whilst not technically supported from this lib, there has been some discussion about it on #40

**Comment by jossmac** [comment]
Ref #142
