### ISSUE TITLE
How to limit  maximum number of toasts 

### ISSUE THREAD

**Issue by Vivek205** [jossmac/react-toast-notifications#64]
I don't find any option to provide limit for the max number of toasts. if there is any, please let know.

**Comment by Vivek205** [comment]
Achieved it through toast stack.
```
const limitToastsNum = (toastStack, removeToast, maxToastsAllowed) => {
  if (toastStack.length > maxToastsAllowed) {
    removeToast(toastStack[0].id);
  }
};
```

**Comment by DominicTobias-b1** [comment]
@Vivek205 when you say you did it through the toast stack, how are you plugging that function into the lib?
