### ISSUE TITLE
Toast should inherit autoDismiss from ToastProvider

### ISSUE THREAD

**Issue by Vivek205** [jossmac/react-toast-notifications#66]
I need to set autoDismiss to true by default.
right now, I'm setting it explicitly whenever I call addToast. It is redundant.
It is better if the Toast could inherit autoDismiss in the same way it inherits the autoDismissTimeout from ToastProvider

**Comment by jossmac** [comment]
@Vivek205 I had implemented this but was worried about unexpected effects in large scale applications. May I recommend exposing your own hook?

```jsx
import { useToasts as useOriginalToasts } from 'react-toast-notifications';

export const useToasts = () => {
  const { addToast, removeToast, toastStack } = useOriginalToasts();

  return {
    addToast: (content, config) => addToast(content, { autoDismiss: true, ...config }),
    removeToast,
    toastStack,
  };
}
```

**Comment by jossmac** [comment]
Closing if favour of #57

**Comment by jossmac** [comment]
The `autoDismiss` property will be inherited from the provided since `2.3.0`
