### ISSUE TITLE
Change font family, font size.

### ISSUE THREAD

**Issue by TrejoCode** [jossmac/react-toast-notifications#68]
Hi, how can I change the font, font size, background colors?

**Comment by jossmac** [comment]
@TrejoCode you can replace the `Toast` component with whatever you like https://github.com/jossmac/react-toast-notifications#replaceable-components

**Comment by TrejoCode** [comment]
I wouldn't want to replace the Toast, just the font size and font

**Comment by jossmac** [comment]
I've added class names to the toast element in `2.3.0` you could target those.

**Comment by Relatora** [comment]
well I add the following code to the css with no effect, any ideas?
`.toast-container{
  font-size: 2em;
}
`
