### ISSUE TITLE
Classes: add a className property or export the ToastElement component

### ISSUE THREAD

**Issue by jsmrcaga** [jossmac/react-toast-notifications#83]
It would be perfect to have a custom class on the default toasts, to allow simple css modifications.

This property could be set as a setting on the provider for example. Another option would be to export the ToastElement component to allow the user to set it as a custom component with a custom className.

**Comment by jossmac** [comment]
Classname support was added in version `2.3.0` #75

**Comment by jsmrcaga** [comment]
Thanks!
