### ISSUE TITLE
Does this work with older versions of react without hooks?

### ISSUE THREAD

**Issue by jakinov** [jossmac/react-toast-notifications#85]
Does this work with older versions of react without hooks?

**Comment by gokuls23** [comment]
i have same doubt, can you upload an example with class component

**Comment by jossmac** [comment]
Hooks were introduced at `2.0.0` as a breaking change. You can use `1.5.x`, here's the [README](https://github.com/jossmac/react-toast-notifications/blob/114e29be946a8565892195e2bb66823654ede69c/README.md) from around that time.

**Comment by sergiop** [comment]
In the newer versions you can still use the HOC:
```js
const AppWithToast = withToastManager(App);
```
Hope this helps.

**Comment by NeliHarbuzava** [comment]
> In the newer versions you can still use the HOC:
> 
> ```js
> const AppWithToast = withToastManager(App);
> ```
> 
> Hope this helps.

How to use it? Where we can find the docs?

**Comment by NeliHarbuzava** [comment]
I found docs here, in old Readme version: https://github.com/jossmac/react-toast-notifications/blob/114e29be946a8565892195e2bb66823654ede69c/README.md

**Comment by sunviwo** [comment]
Please make HOC available in new versions too. Thanks in advance

**Comment by sergiop** [comment]
@sunviwo is still available:
https://github.com/jossmac/react-toast-notifications/blob/e1607a56676dd6b7711ef3744270dee5c42933cb/src/index.js#L6

Take a look into the old readme to understand how to use it 😉

**Comment by sunviwo** [comment]
Thanks @sergiop. I just tried it and it worked like a charm. :)
