### ISSUE TITLE
Call directly without being in a component?

### ISSUE THREAD

**Issue by burtonator** [jossmac/react-toast-notifications#86]
Is there a way to call this directly without it being used in a component?

I have some plain java functions that can reach out and create toasts and I want to just replace it with this.

The only way I could think of is to create a wrapper and inject it , then have a function that calls it indirectly via a ref or something (thinking out loud).

Would be nice if there was just a static addToast function I could call.

**Comment by jossmac** [comment]
Hi @burtonator, I'm afraid that this is very much a React solution, though you may find the thread on #40 helpful.

Please see [alternatives](https://github.com/jossmac/react-toast-notifications#alternatives) or perhaps [npm](https://www.npmjs.com/search?q=keywords:toast). Also, please feel free to grab any of the elements you like from this repo and create your own store + pub/sub system.

**Comment by alisternorris** [comment]
I created a small package to address this issues: https://github.com/alisternorris/react-outside-call
