### ISSUE TITLE
addToast causes entire application to unmount and rerender

### ISSUE THREAD

**Issue by kjr247** [jossmac/react-toast-notifications#87]
In my react web application when the addToast is fired it causes everything to rerender. 
It looks like all components in the application are unmounting. 

This causes all components using component state and hooks to lose their data. These components are fetching data, and refetching data causing long loading times.

Is this a bug or are we doing something wrong? I couldn't find anything in the examples or docs to explain this.

```javascript
addToast(toastSuccessMessage, {
        appearance: ToastAppearance.SUCCESS,
        autoDismiss: true,
      });

const ToastContainerOverride = (props: any) => (
  <DefaultToastContainer
    className="toast-container"
    style={{ }}
    {...props}
  />
);


const App = () => (
  <Fragment>
    <GlobalStyle />
    <ThemeProvider theme={theme}>
      <ToastProvider components={{ ToastContainer: ToastContainerOverride }}>
        <Provider store={store}>
          <Routing />
        </Provider>
      </ToastProvider>
    </ThemeProvider>
  </Fragment>
);
```

**Comment by kjr247** [comment]
I figured it out finally! The thing is that Routing contained a RouteGaurd component that passed withToastManager to toastManager.add(...). This was causing the entire tree to unmount for some reason. I found this by monkeypatching/editing the package to concole.log the onDismiss, and it showed a remove method. I made a couple of logical jumps to realize something else was updating values that were somehow being passed down from the top level components. Finding the offending 

```javascript
export default connect(
  mapStateToProps,
  mapDispatchToProps
)(withToastManager(withRouter(RouteGuard)));
```

and made it into 

```javascript
export default connect(
  mapStateToProps,
  mapDispatchToProps
)(withRouter(RouteGuard));
```

**Comment by kjr247** [comment]
Well it turns out this broke the call after all. The RouteGaurd component is a class component, and thus cannot call this method. const { addToast } = useToasts();

error message:
Unhandled Rejection (Invariant Violation): Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app

**Comment by ngmiduc** [comment]
I don't really understand your solution. Did you find a way to prevent rerendering in ToastProvider ?

**Comment by kjr247** [comment]
I'm in the process of moving all of our code out to a dumb component. 
It will take time, but I think this is my fix. It wasn't super obvious because I wasn't super familiar with using hooks at the time.

As I was moving it all out I discovered that the developer who added it directly to the RouteGaurd.tsx class component had already created a placeholder dumb component somewhere with a todo to move all of the code there instead of in the class component. 👍

**Comment by ngmiduc** [comment]
Eventually, I think that is a werid behaviour. I am struggling a bit myself. Why does the entire App rerenders when the toasts appear and disappear. As you said, all the data will be reset. That is kind of bizarre, since it would be cool if the state can remain while adding and removing toasts.

Someone has other thoughts ?

**Comment by jossmac** [comment]
@ngmiduc are you also replacing the default components? That could explain the re-render that's potentially causing children to unmount/remount.

```jsx
// react will re-render this because the object `components` is different by reference
<ToastProvider components={{ ToastContainer: ToastContainerOverride }}>
```

```jsx
// you should define the components object beforehand so there's no change during React's diffing stage
const TOAST_COMPONENTS = { ToastContainer: ToastContainerOverride }
...
<ToastProvider components={TOAST_COMPONENTS}>
```

**Comment by brussev** [comment]
> @ngmiduc are you also replacing the default components? That could explain the re-render that's potentially causing children to unmount/remount.
> 
> ```js-jsx
> // react will re-render this because the object `components` is different by reference
> <ToastProvider components={{ ToastContainer: ToastContainerOverride }}>
> ```
> 
> ```js-jsx
> // you should define the components object beforehand so there's no change during React's diffing stage
> const TOAST_COMPONENTS = { ToastContainer: ToastContainerOverride }
> ...
> <ToastProvider components={TOAST_COMPONENTS}>
> ```

Hey @ngmiduc,
I have the same issue and I couldn't fix it with your proposal. On show/hide there is one more re-render on the app.
Do you know what else can cause the re-rendering the app on show/hide?
I am using version `2.4.4` of `react-toast-notifications`
![Screenshot 2020-09-02 at 16 18 34](https://user-images.githubusercontent.com/45165261/91988461-f5bcd980-ed37-11ea-8f1a-34ed9c2f3ed8.png)

**Comment by latanoel** [comment]
Has anyone been able to solve this? I'm facing the same issue. Entire app re-renders whenever toast appears or disappears.

**Comment by martinnemec3** [comment]
I had a similar issue - when I added a toast the content of my <Route> component was re-rendering. After some time of playing with the code I found that it happens only when my route content is defined via the component parameter function.

When I switched to definition via the JSX tag content, it started to work and the re-rendering disappeared.

so previously I had something like:
`<Route exact path="/" component={() => <Home />}>`

then I changed it to:
`<Route exact path="/"><Home /></Route>`

This solution helped to me however I still do not understand what's behind exactly.

**Comment by alexsro** [comment]
I had de same issue, any solution?

**Comment by cvjude** [comment]
I had a similar issue where my App would re-render and I'd lose all my component state
What I did was to wrap the component that would use the toast with the ToastProvider
So aside from the ToasProvider wrapping my entire app, I wrapped the component that I wanted to use the toast with, and this worked.

I think the issue may have been caused by the depth of my routing

My app component
```
ReactDOM.render(
  <Provider store={store}>
    <ToastProvider>
      <Appz />
    </ToastProvider>
  </Provider>,
  document.getElementById('root')
);
```

the component where I used the toast
```
return (
    <>
      <Nav
        currentCohort={currentCohort}
        currentCourse={currentCourse}
        link={`${pathname}/add`}
        text="Add Class"
      />
      <NavBar />
      <section className="cx_listnx img">
        {loading ? (
          <Loader tempLoad={true} full={false} />
        ) : (
          <ToastProvider>
            <AddNewClass
              name={currentCourse.name}
              courseId={courseId}
              mainCohortId={currentCohort.Cohort.id}
            />
          </ToastProvider>
        )}
      </section>
    </>
```

I hope this helps someone

**Comment by amoskeyz** [comment]
> I had a similar issue where my App would re-render and I'd lose all my component state
> What I did was to wrap the component that would use the toast with the ToastProvider
> So aside from the ToasProvider wrapping my entire app, I wrapped the component that I wanted to use the toast with, and this worked.
> 
> I think the issue may have been caused by the depth of my routing
> 
> My app component
> 
> ```
> ReactDOM.render(
>   <Provider store={store}>
>     <ToastProvider>
>       <Appz />
>     </ToastProvider>
>   </Provider>,
>   document.getElementById('root')
> );
> ```
> 
> the component where I used the toast
> 
> ```
> return (
>     <>
>       <Nav
>         currentCohort={currentCohort}
>         currentCourse={currentCourse}
>         link={`${pathname}/add`}
>         text="Add Class"
>       />
>       <NavBar />
>       <section className="cx_listnx img">
>         {loading ? (
>           <Loader tempLoad={true} full={false} />
>         ) : (
>           <ToastProvider>
>             <AddNewClass
>               name={currentCourse.name}
>               courseId={courseId}
>               mainCohortId={currentCohort.Cohort.id}
>             />
>           </ToastProvider>
>         )}
>       </section>
>     </>
> ```
> 
> I hope this helps someone

This worked for me.
