### ISSUE TITLE
Move units from px to rem.

### ISSUE THREAD

**Issue by sergiop** [jossmac/react-toast-notifications#92]
Hi @jossmac, first of all, my compliments for this project.
I've seen all the units are in PX. This is a truly limiting notion and I would move to REM to allow us to use this module also on modern responsive projects.
What do you think? If I send you a PR, will you take it into consideration?

**Comment by jossmac** [comment]
Hi @sergiop, thanks for the kind words.

I'm not really comfortable moving to rems. It would be a breaking change to the lib because we can't guarantee a consistent root font-size for every consumer, which would lead to unexpected results.

You can however style your implementation however you like 🙂

**Comment by sergiop** [comment]
I understand that it would be a big change (under the hood perhaps), but I'm not sure it would be a breaking one. In the end, the majority of the users are using this module with the default root-font size, 16px, if we remap 16px to 1rem, this means that nothing will change for all of them. But moving to REM allow who use this module in a modern project to bring out the best from it. 

A further note: it isn't only a matter of style since some measurements are computed and are not overwritable with CSS.

I understand that you have doubts, but I think you can move forward to the next level. 😉

**Comment by sergiop** [comment]
About the unexpected results, you can drive the transition from px to rem with a prop, something like `rootFontSize`, expressed in PX, to fix the px to rem conversion for those projects don't need this feature.

**Comment by sergiop** [comment]
On second thought, you can give to `rootFontSize` the default value of `16px`, this guarantee 100% of backward compatibility and allows who wants to unlock rem power to set it to `1rem`.
