### ISSUE TITLE
Toast disappears and then reappears on first load and after changing routes

### ISSUE THREAD

**Issue by lvwrence** [jossmac/react-toast-notifications#95]
Hiya, thanks for this awesome library! Everything works great so far, except this small UI issue where it seems like on the first notification shown on the page and after changing routes, the toast briefly zooms to the right and then shows up correctly. Here's a GIF showing what I mean:

![Mar-12-2020 17-43-33](https://user-images.githubusercontent.com/963922/76569302-29a1fb00-6489-11ea-8ada-922860ff4bce.gif)

Have you seen this before / do you know how to resolve it? My code here basically follows the docs in terms of usage, not doing anything weird (I think).

**Comment by lvwrence** [comment]
ok so that was happenign when transitionState === 'exited', seems like it was already there and trying to rush to the entry point state?

I made a custom component that checked for transitionState === 'exited' and return null in that case.

**Comment by pablo-abc** [comment]
I am having the same issue whenever an element containing [react-textarea-autosize](https://github.com/andreypopp/react-textarea-autosize) is present anywhere on the page.

Here's a [reproduction on codesandbox](https://codesandbox.io/s/textareaautosize-issue-ih86q?file=/src/App.js). You'll notice that if `<TextareaAutosize />` is present, it behaves like in your example. If you remove that line it works correctly.

I managed to fix it with your solution but it feels a bit hacky, maybe this issue should be reopened? It is a minor issue but quite annoying nonetheless.
