### ISSUE TITLE
How to use toast notification in class component

### ISSUE THREAD

**Issue by IrtazaHussain1** [jossmac/react-toast-notifications#98]
Hi, I am new to react and want to use this react notification in my project. I am using the class base component and all tutorials and doc are on function base component and using hooks. I there anything you guys can guide me on how to use addToast Hook in class base component.

**Comment by zohaibijaznbs** [comment]
@IrtazaHussain1 Here is how you can use this with class components by creating a higher order comonent
```
import { useToasts } from 'react-toast-notifications'

function withToast(Component) {
  return function WrappedComponent(props) {
    const toastFuncs = useToasts()
    return <Component {...props} {...toastFuncs} />;
  }
}

//In you class component file

class MyComponent extends Component {

  componentDidMount () {
    this.props.addToast('Hello Toast');
  }
  
  render () {
    return <div>Toasts</div>
  }
}

export default withToast(MyComponent);
```

**Comment by IrtazaHussain1** [comment]
thanks

**Comment by IrtazaHussain1** [comment]
@zohaibijaznbs  this error I am facing
"The `useToasts` hook must be called from a descendent of the `ToastProvider`."

**Comment by jossmac** [comment]
@IrtazaHussain1 you must wrap your app with the `ToastProvider` to have access to it's context elsewhere within your app.

https://github.com/jossmac/react-toast-notifications#use
