### ISSUE TITLE
Add Toast using Redux Actions 

### ISSUE THREAD

**Issue by mohsinht** [jossmac/react-toast-notifications#99]
I'm not sure if its already done but I cannot find anything related to Redux in the documentation.

I'm looking for a solution where I can invoke '`addToast(content)`' using Redux Actions. For example if I'm fetching data then the toast must display '`loading'` state and then  `'success'`/`'failure'` on response.

**Comment by armenzest** [comment]
+1. I've been trying to see if theres a way to do this as well.

**Comment by paolocattani** [comment]
any updates ?

**Comment by gadiGuesty** [comment]
One solution could be passing the hook to your action:
`const ConnectedComponent = () => {`
  `const { addToast } = useToasts();`
 `const dispatch = useDispath();`
 `const handler = () => dispatch(myAction(addToast))`
`return<div>...`
`}
`

`const myAction = (addToast) => {
addToast(...)
return{
...
}
}`

**Comment by Hainesy** [comment]
I've resorted to adding messages to global state in redux then have a component that subscribes to those.

```ts
const ToastMessageHandler: FC = () => {
  const messages = useSelector(
    (state: RootState) => state.global.messages,
    (l, r) => l.length === r.length
  );
  const { clearMessages } = useDispatch<Dispatch>().global;
  const { addToast } = useToasts();
  useEffect(() => {
    if (messages && messages.length) {
      messages.forEach((message) => {
        addToast(message.message, { appearance: message.type });
      });
      setTimeout(() => clearMessages());
    }
  }, [messages]);
  return null;
};
```

**Comment by ptsteadman** [comment]
This library might be a better fit fo this use case, or a reference for implementing a redux wrapper for this toast system: https://www.npmjs.com/package/react-notification-system-redux

**Comment by gadiGuesty** [comment]
You might consider use [react-toastify/](https://fkhadra.github.io/react-toastify/) which has event emitter as it's mediator and is not dependent on React context api.

**Comment by ericblade** [comment]
FWIW, @Hainesy 's solution seems to work pretty well.  I've implemented that along with an action that adds to the toast list, and an action that erases the toast list.  Areas for potential improvement in that solution would actually include clearing the list immediately after adding the toasts, and/or ensuring you never add the same toast twice with some sort of serial number on them.  

I think ideally there would be some way to write a middleware that accepts a message, then turns it into a toast, but I'm not seeing a quick way there given the existing library.  Perhaps a library that wraps this in a similar component to @hainesy's and also provides a redux middleware to get to it.  Maybe I'll do some quick prototyping of that.

**Comment by jossmac** [comment]
Ref #142
